services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: montink_erp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      - redis
    networks:
      - montink_erp

  nginx:
    image: nginx:alpine
    container_name: montink_erp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - montink_erp

  mysql:
    image: mysql:8.0
    container_name: montink_erp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: montink_erp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: montink
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - montink_erp

  redis:
    image: redis:7-alpine
    container_name: montink_erp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - montink_erp

  mailpit:
    image: axllent/mailpit
    container_name: montink_erp_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - montink_erp

  queue:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: montink_erp_queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan queue:work --sleep=3 --tries=3
    depends_on:
      - mysql
      - redis
    networks:
      - montink_erp

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  montink_erp:
    driver: bridge